server:
  port: 9000
  tomcat:
    uri-encoding: UTF-8
    max-http-header-size: 80KB

spring:
  profiles:
    active: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    data-username: root
    data-password: root
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 600000
      pool-name: DateSourceHikaricp
      max-lifetime: 180000
      connection-test-query: SELECT 1
    url: jdbc:mysql://120.25.171.171:3306/blog?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: succos
    password: succos
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 
    jedis:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms
    timeout: 500000
mybatis:
  type-aliases-package: com.succos.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


mapper:
  mappers: com.succos.my.mapper.MyMapper
  not-empty: false
  identity: MYSQL

